name: GitHub Actions Master
on:
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Job started info
        run: |
          echo "ðŸŽ‰ This job was automatically triggered by ${{ github.event_name }} event."
          echo "ðŸ§ Running on ${{ runner.os }} hosted by GitHub!"
          echo "ðŸ”Ž Branch: ${{ github.ref }}, Repository: ${{ github.repository }}"
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: |
            github.com
            ${{ secrets.SSH_HOST }}
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
      - name: Set deploy script permission
        run: chmod +x ./deploy.sh
      - name: Deploy on test environment
        run: ssh root@${{ secrets.DEPLOY_HOST }} 'bash -s' < ./deploy.sh
      - name: Done
        run: echo "ðŸ“¦ Deployment finished"
